### ISSUE TITLE
ImportError: cannot import name 'CpuViterbiPath' from 'flashlight.lib.sequence.criterion'

### ISSUE THREAD

**Issue by asadullah797** [flashlight/sequence#21] opened 2024-04-07 16:23 UTC
When I run this command:
python3 examples/speech_recognition/infer.py (with other parameters)
I get the following error:
ImportError: cannot import name 'CpuViterbiPath' from 'flashlight.lib.sequence.criterion'

Then I go deeper into the problem and find out in infer.py file that when I import in python
from flashlight.lib.text.dictionary import create_word_dict, load_words
it works fine. However when I try to import 
from flashlight.lib.sequence.criterion import CpuViterbiPath, get_data_ptr_as_bytes
it raises an exception of 
ImportError: cannot import name 'CpuViterbiPath' from 'flashlight.lib.sequence.criterion'

I am using the latest fairseq, sequence and text packages.

**Comment by jacobkahn** [comment] 2024-04-09 21:56
Duplicate of https://github.com/flashlight/sequence/issues/19. Fix is landing now.

**Closed as completed by jacobkahn** 2024-04-09 21:56 UTC
